version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bugun_ne_giysem_backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bugun_ne_giysem_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
